config/routes.rb
FurnitureStore::Application.routes.draw do

  resources :furnishings

  match 'furniture' => 'furnishings#index'
  match 'furniture/:id' => 'furnishings#show'

  resources :contact, :only => [:index, :create]

  match 'about' => 'about#index'

  root :to => 'main#index'

end

app/views/shared/_analytics.html.erb
    <!-- GoogleAnalytics -->
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-11370325-1']);
      _gaq.push(['_trackPageview']);
      (function() {
       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
       })();
     </script>

app/views/shared/_dimension.html.erb
        <li><%= dimension %></li>

app/views/shared/_dimension_list.html.erb
      <ul>
        <%= render :partial=>'shared/dimension', :collection=>dimensions %>
      </ul>

app/views/shared/_footer.html.erb
        <div id='footer'>
          <div class='container'>
            <p>&copy; Copyright 2009 Balmain &amp; Balmain. All Rights Reserved.</p>
          </div>
        </div>

app/views/shared/_item.html.erb
      <li>
        <dl>
          <dt><%= link_to(item.shape.capitalize, item) %></dt>
          <dd>
            <%= link_to truncate(item.description, :length => 35), item %>
          </dd>
          <dd>
            <%= link_to(image_tag(image_path(img_name_determiner(item.img, "thumb")), :alt=>item.name, :class=>'thumb', :title=>item.name), item) %>
          </dd>
        </dl>
      </li>

app/views/shared/_item_list.html.erb
<div class='row'>
  <ul class='features'>
    <% for item in items -%>
    <%= render :partial => "shared/item", :locals => { :item => item } %>
    <% end -%>
  </ul>
</div><!-- End:row -->

app/views/shared/_menu.html.erb
          <ul class='menu'>
            <%= menu_item('home', root_path) %>
            <%= menu_item('furniture', furnishings_path) %>
            <%= menu_item('about', '/about') %>
            <%= menu_item('contact', '/contact') %>
          </ul>

app/views/shared/_range.html.erb
        <li>
          <dl>
            <dt><%= link_to(range.name, range) %></dt>
            <dd>
              <%= link_to range do %>
                <%= image_tag(image_path(img_name_determiner(range.img, "thumb")), :alt=>range.name, :class=>'thumb', :title=>range.name) %>
              <% end %>
            </dd>
          </dl>
        </li>

app/views/shared/_range_list.html.erb
    <div class="span-20 last">
      <h3>Alternatives in this <%= @furnishing.shape.capitalize %> Range</h3>
      <ul class="ranges">
        <%= render :partial=>'shared/range', :collection=>range %>
      </ul>
    </div>
    <div class="clear"></div>